### ISSUE TITLE
Using miniconda as basic python but installing Python packages highlights bug in shapely-1.8.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#81]
### Steps to reproduce

Importing `cartopy` in Python 3 fails if using a basic miniconda as Python interpreter and installing everything (`geos`, `cartopy`, _shapely_, ...) with `spack`, because it can't find `libgeos_c.so`.

This is from shapely's `lib/python3.9/site-packages/shapely/geos.py`:
```
_lgeos = None
def exists_conda_env():
    """Does this module exist in a conda environment?"""
    return os.path.exists(os.path.join(sys.prefix, 'conda-meta'))


if sys.platform.startswith('linux'):
    # Test to see if we have a wheel repaired by auditwheel which contains its
    # own libgeos_c. Note: auditwheel 3.1 changed the location of libs.
    geos_whl_so = glob.glob(
        os.path.abspath(os.path.join(os.path.dirname(__file__), ".libs/libgeos*.so*"))
    ) or glob.glob(
        os.path.abspath(
            os.path.join(
                os.path.dirname(__file__), "..", "Shapely.libs", "libgeos*.so*"
            )
        )
    )

    if len(geos_whl_so) > 0:
        # We have observed problems with CDLL of libgeos_c not automatically
        # loading the sibling c++ library since the change made by auditwheel
        # 3.1, so we explicitly load them both.
        geos_whl_so = sorted(geos_whl_so)
        CDLL(geos_whl_so[0])
        _lgeos = CDLL(geos_whl_so[-1])
        LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)

    elif hasattr(sys, 'frozen'):
        geos_pyinstaller_so = glob.glob(os.path.join(sys.prefix, 'libgeos_c-*.so.*'))
        if len(geos_pyinstaller_so) >= 1:
            _lgeos = CDLL(geos_pyinstaller_so[0])
            LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
    elif exists_conda_env():
        # conda package.
        _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
    else:
        alt_paths = [
            'libgeos_c.so.1',
            'libgeos_c.so',
        ]
        _lgeos = load_dll('geos_c', fallbacks=alt_paths)
```

Because it thinks this is a conda env it is looking for `/work/noaa/da/jedipara/spack-stack/miniconda-3.9.7/lib/libgeos_c.so` instead of simply trying to load the `geos` libraries and only try to be smarter than the user if that fails.

### Error message

```
Orion-login-3[80] dheinzel$ python3
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-cartopy-0.18.0-sjcyvgi/lib/python3.9/site-packages/cartopy/__init__.py", line 96, in <module>
    import cartopy.crs
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-cartopy-0.18.0-sjcyvgi/lib/python3.9/site-packages/cartopy/crs.py", line 32, in <module>
    import shapely.geometry as sgeom
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-shapely-1.8.0-35vzwqm/lib/python3.9/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-shapely-1.8.0-35vzwqm/lib/python3.9/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-shapely-1.8.0-35vzwqm/lib/python3.9/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/work/noaa/da/role-da/spack-stack/spack-stack-v0.0.1/envs/jedi-all-intel-2022.1.2/install/intel/2022.0.2/py-shapely-1.8.0-35vzwqm/lib/python3.9/site-packages/shapely/geos.py", line 93, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/work/noaa/da/jedipara/spack-stack/miniconda-3.9.7/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /work/noaa/da/jedipara/spack-stack/miniconda-3.9.7/lib/libgeos_c.so: cannot open shared object file: No such file or directory
>>>
```

### Information on your system

```
[jedi-all-intel-2022.1.2] 563 role-da@Orion-login-2 spack-stack-v0.0.1 ❯❯❯ spack debug report
uname -a
* **Spack:** 0.18.0.dev0
* **Python:** 3.9.12
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
[jedi-all-intel-2022.1.2] 564 role-da@Orion-login-2 spack-stack-v0.0.1 ❯❯❯ uname -a
Linux Orion-login-2.HPC.MsState.Edu 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by climbfuji** [comment]
There were major updates in shapely between version 1.8.0 - which we have to use, according to - and the latest code, therefore we can't ask for changes in shapely but have to add a patch in our spack for for it.

**Comment by climbfuji** [comment]
Workaround / possible patch in our spack fork is to simple comment out these three lines:
```
    #elif exists_conda_env():
    #    # conda package.
    #    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
```

**Comment by climbfuji** [comment]
I just fixed this, without remember that I came across this earlier. See https://github.com/NOAA-EMC/spack-stack/issues/299 and https://github.com/NOAA-EMC/spack-stack/pull/300.
